name: Push checks
on: [pull_request, push]

permissions: read-all

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0
      - name: Install Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test
  coverage:
    name: Test Coverage
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0
      - name: Install Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run unit test with coverage
        run: npm run coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./reports/coverage/lcov.info
  mutation:
    name: Mutation Test
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0
      - name: Install Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run mutation test
        run: npm run test:mutation
  property:
    name: Property Tests
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0
      - name: Install Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run property tests
        run: npm run test:property
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0
      - name: Install Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  transpile:
    name: Transpile to CommonJS
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0
      - name: Install Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Transpile to CommonJS
        run: npm run transpile
      - name: Test transpiled code
        run: npm run test:transpiled
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0
      - name: Install Ruby
        uses: ruby/setup-ruby@v1.87.0
        with:
          ruby-version: 2.7
      - name: Setup cache for gems
        uses: actions/cache@v2.1.7
        with:
          path: docs/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install Jekyll
        working-directory: docs
        run: |
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
      - name: Build website
        working-directory: docs
        run: bundle exec jekyll build
