name: Test and Lint
on: [pull_request, push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.12.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm run test

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.12.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm run lint
